### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by peterwiebe** [shahradelahi/next-extra#10]
This is a great utility, thanks for publishing it. I was wondering if you have any intentions to add types for Typescript?
![Screenshot 2024-06-13 at 10 50 22 AM](https://github.com/shahradelahi/next-extra/assets/3029679/4ed6edc6-8efe-49ac-b912-9a15e8843686)

**Comment by peterwiebe** [comment]
Also, seem to be getting this error after following your readme
![Screenshot 2024-06-13 at 11 23 54 AM](https://github.com/shahradelahi/next-extra/assets/3029679/2a46c7c0-0603-452d-a52f-f87be413a200)
I am on NextJS 1.14.1

**Comment by shahradelahi** [comment]
In your `tsconfig.json` file, change the `compilerOptions.moduleResolution` to `Bundler`.

**Comment by shahradelahi** [comment]
> I am on NextJS 1.14.1

I'm sorry, which version are you using? I developed the package on the latest version of NextJS, and the feature I used was introduced in `14.2.0` (or `14.1.1-canary.9`).

I'm going to start working on a solution to make it compatible, but I highly recommend you update because you are missing out on tons of improvements and bug fixes. For most users, the update process is simply changing the version of the dependency. You can read the changelogs here: https://nextjs.org/blog/next-14-2
